# src/main/resources/application.properties (o el que esté cargando tu app)
spring.application.name=franchise-api
server.port=8084

spring.data.mongodb.uri=mongodb://root:example@localhost:27017/
spring.data.mongodb.database=franchise_db
spring.data.mongodb.auto-index-creation=true

